[package]
name = "code-spaces-test"
version = "0.1.0"
authors = ["Jacob Gonzalez <jacobgonzalez5252@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
